/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  safelist: [
    'backdrop-blur-xl',
    'bg-accent/20',
    'bg-bg',
    'bg-bg/70',
    'bg-surface/70',
    'border',
    'border-b',
    'border-slate-300/20',
    'border-slate-300/40',
    'dark:border-slate-700',
    'dark:border-slate-700/40',
    'flex',
    'flex-col',
    'flex-wrap',
    'font-bold',
    'font-semibold',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-5',
    'grid',
    'h-10',
    'h-16',
    'hidden',
    'hover:bg-surface/60',
    'hover:scale-[1.03]',
    'hover:shadow-glow',
    'hover:text-text',
    'inline-flex',
    'items-center',
    'items-start',
    'justify-between',
    'justify-center',
    'leading-7',
    'leading-tight',
    'lg:grid-cols-2',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'mb-8',
    'md:flex',
    'md:flex-row',
    'md:hidden',
    'md:items-center',
    'md:items-end',
    'md:justify-between',
    'md:mb-10',
    'md:p-7',
    'md:text-4xl',
    'md:text-6xl',
    'md:text-base',
    'min-h-screen',
    'ml-2',
    'mt-1',
    'mt-2',
    'mt-3',
    'mt-4',
    'mt-5',
    'mt-6',
    'mt-8',
    'overflow-x-auto',
    'overflow-x-clip',
    'p-6',
    'pb-3',
    'px-2',
    'px-3',
    'py-1',
    'py-2',
    'py-8',
    'rounded-full',
    'rounded-md',
    'rounded-xl',
    'shrink-0',
    'sm:grid-cols-2',
    'space-y-3',
    'space-y-4',
    'sticky',
    'text-2xl',
    'text-4xl',
    'text-accent',
    'text-base',
    'text-lg',
    'text-muted',
    'text-sm',
    'text-text',
    'text-xl',
    'text-xs',
    'top-0',
    'tracking-tight',
    'tracking-widest',
    'transition',
    'uppercase',
    'w-10',
    'z-40',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--color-bg) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        text: 'rgb(var(--color-text) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
      },
      boxShadow: {
        glow: '0 10px 30px rgba(45, 212, 191, 0.2)',
      },
    },
  },
  plugins: [],
};
